name: Prebuild the binaries.

on:
  workflow_dispatch:
  push:

jobs:
  prebuild:
    strategy:
      matrix:
        os: [windows]
        node: [16]
    runs-on: ${{ matrix.os }}-latest
    env: 
      VCINSTALLDIR: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - if: ${{ matrix.os == 'windows' }}
        shell: powershell
        run: |
          npm config set msvs_version 2022 -g
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
      - run: npm install --ignore-scripts
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.node }}
          path: build/Release/qjsc_20210327.node
