name: Prebuild the binaries.

on:
  workflow_dispatch:
  push:

jobs:
  prebuild:
    strategy:
      matrix:
        os: [windows-2016]
        node: [12, 14, 16, 18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - if: ${{ matrix.os == 'windows' }}
        run: npm config set msvs_version 2017
      - run: npm install --ignore-scripts
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.node }}
          path: build/Release/qjsc_20210327.node
