name: Prebuild the binaries.

on:
  workflow_dispatch:
  push:

jobs:
  prebuild:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12, 14, 16, 18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install --ignore-scripts
      - run: npm run prebuild
      - uses: actions/upload-artifact@v3
          with:
          name: ${{ matrix.os }}-${{ matrix.node }}
          path: build/
